from __future__ import annotations

"""Explainability router for public graph exploration.

This module exposes a simple endpoint returning a subgraph and attention
scores around a given node as well as a base64 encoded SVG visualisation.
The route requires authentication via the ``X-API-Key`` header so it can
be used from demo pages.
"""

import base64
import json

from fastapi import APIRouter, Depends, Header, HTTPException, Query
from fastapi.responses import JSONResponse

from datacreek.analysis import explain_to_svg, top_k_incoherent
from datacreek.backends import get_neo4j_driver, get_redis_client
from datacreek.core.dataset import DatasetBuilder
from datacreek.db import SessionLocal, User
from datacreek.services import get_user_by_key

router = APIRouter(prefix="/explain", tags=["explain"])


def get_current_user(api_key: str = Header(..., alias="X-API-Key")) -> User:
    """Authenticate using the API key stored in the database or Redis."""
    with SessionLocal() as db:
        user = get_user_by_key(db, api_key)
        if not user:
            raise HTTPException(status_code=401, detail="Invalid API key")
        return user


def _load_dataset(name: str, user: User) -> DatasetBuilder:
    """Return ``DatasetBuilder`` for ``name`` if accessible by ``user``."""
    client = get_redis_client()
    if client is None:
        raise HTTPException(status_code=404, detail="Dataset not found")
    try:
        driver = get_neo4j_driver()
        ds = DatasetBuilder.from_redis(client, f"dataset:{name}", driver)
    except KeyError:
        raise HTTPException(status_code=404, detail="Dataset not found")
    finally:
        if driver:
            driver.close()
    if ds.owner_id not in {None, user.id}:
        raise HTTPException(status_code=404, detail="Dataset not found")
    ds.redis_client = client
    return ds


@router.get("/sheaf_diff", summary="List incoherent sheaf edges")
def sheaf_diff(
    dataset: str = Query("demo", alias="dataset"),
    top: int = Query(50, ge=1),
    tau: float = Query(0.0, ge=0.0),
    user: User = Depends(get_current_user),
) -> JSONResponse:
    """Return up to ``top`` edges with spectral mismatch > ``tau``.

    The dataset is converted to a NetworkX graph and passed to
    :func:`top_k_incoherent` which computes the change in eigenvalue
    discrepancies when removing each edge.  The response contains the list
    of edges sorted by this difference.
    """

    ds = _load_dataset(dataset, user)
    g = getattr(ds, "graph", None)
    if callable(g):
        g = g()
    if g is None:
        conv = getattr(ds, "to_networkx", None)
        g = conv() if callable(conv) else None
    if g is None:
        raise HTTPException(status_code=404, detail="Graph not found")
    data = top_k_incoherent(g, top, tau)
    payload = [{"u": u, "v": v, "delta": d} for (u, v), d in data]
    return JSONResponse({"edges": payload})


@router.get("/repair_preview", summary="Preview repair suggestions")
def repair_preview(
    limit: int = Query(5, ge=1, le=100),
    user: User = Depends(get_current_user),
) -> JSONResponse:
    """Return up to ``limit`` stored repair suggestions.

    Suggestions are generated by :mod:`cron.sheaf_repair` and stored in the
    ``repair_suggestions`` list in Redis."""
    client = get_redis_client()
    items = []
    if client is not None:
        raw = client.lrange("repair_suggestions", 0, limit - 1)
        items = [json.loads(r) for r in raw]
    return JSONResponse({"suggestions": items})


@router.get("/{node}", summary="Explain node neighborhood")
def explain_node_public(
    node: str,
    dataset: str = Query(
        "demo",
        alias="dataset",
        examples={"default": {"summary": "Demo dataset", "value": "demo"}},
    ),
    hops: int = Query(3, ge=1, le=5),
    user: User = Depends(get_current_user),
) -> JSONResponse:
    """Return explanation data for ``node`` in ``dataset``.

    The response contains the neighborhood ``nodes`` and ``edges`` lists,
    an ``attn`` mapping for attention scores and a base64 encoded ``svg``
    rendering of the subgraph.

    Example
    -------

    ``curl``::

        curl -H "X-API-Key: <token>" \
             "http://localhost:8000/explain/foo?dataset=demo"

    JavaScript ``fetch``::

        fetch("/explain/foo?dataset=demo", {
            headers: {"X-API-Key": "<token>"}
        }).then(r => r.json());
    """

    ds = _load_dataset(dataset, user)
    data = ds.explain_node(node, hops=hops)
    svg = explain_to_svg(data)
    payload = {
        "nodes": data.get("nodes", []),
        "edges": data.get("edges", []),
        "attn": data.get("attention", {}),
        "svg": base64.b64encode(svg.encode()).decode(),
    }
    return JSONResponse(payload)
